name: wisetrack_example
description: "Demonstrates how to use the wisetrack plugin."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+5

environment:
  sdk: ^3.7.0
  # sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_custom_dropdown: ^3.1.1

  wisetrack:
    path: ../
  flutter_inappwebview: ^6.1.5
  webview_flutter: ^4.13.0
  firebase_core: 2.32.0
  firebase_messaging: 14.7.10

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/html/
